### ISSUE TITLE
Build: wrong default value of PREFIX in config.mk

### ISSUE THREAD

**Issue by emanuele6** [phillbush/pmenu#1]
`README` states:

    By default, πmenu is installed into the /usr/local prefix.  Enter the
    following command to install πmenu (if necessary as root).  This command
    installs the binary file ./pmenu into the ${PREFIX}/bin/ directory, and
    the manual file ./pmenu.1 into ${MANPREFIX}/man1/ directory.
    
        make install

But, in `config.mk`, `PREFIX` and `MANPREFIX` are defined as:

    # paths
    PREFIX = ../..
    MANPREFIX = ${PREFIX}/man

This settings will cause `make install` to install, by default, `pmenu` in `../../bin` and `pmenu.1` in `../../man/man1` which is very weird as a default and is not coherent with what is written in `README`.

Also note that, in [xmenu](https://github.com/phillbush/xmenu)'s default [config.mk](https://github.com/phillbush/xmenu/blob/d584fba62674833135a9cb3eb9ec0f0e3fe96743/config.mk), `MANPREFIX` is set to `${PREFIX}/share/man`, while the default value for `pmenu` is `${PREFIX}/man`.

**Comment by phillbush** [comment]
> This settings will cause make install to install, by default, pmenu in ../../bin and pmenu.1 in ../../man/man1 which is very weird as a default and is not coherent with what is written in README.

Fixed by the last commit.

That weird defaults is because in my system, I install things at ~/usr, and build things at ~/usr/src/pmenu. I must have forgotten to change the defaults for release.
