### ISSUE TITLE
When run with the -r flag, pmenu opens the menu whenever the button is pressed, not only on the root window.

### ISSUE THREAD

**Issue by magnus-ISU** [phillbush/pmenu#10]
Steps to reproduce: install dwm, open a window, run

```
pmenu -r 3 <<!
a
b
!
```

right click on the window, pmenu still opens a menu.

Expected behaviour: This only happens when clicking on the root window, like what happens with `xsetroot`.

**Comment by phillbush** [comment]
Fixed!

The behavior was  actually theexpected when a modifier was provided with the `-m` option.  Since I always use pmenu with the -m option I never realized it didn't work without it.
