### ISSUE TITLE
Fonts broken?

### ISSUE THREAD

**Issue by GanerCodes** [phillbush/pmenu#13]
I'm not sure what happened but after a plasma update text just stopped rendering. No idea why

**Comment by phillbush** [comment]
There's not much I can do with so few information.

Try to run pmenu on a terminal and check whether it outputs any error.  
Also try to manually set Xresources for pmenu on your ~/.Xresources or ~/.Xdefaults file. KDE often overrides X11 resources.

**Comment by GanerCodes** [comment]
I tried putting this into ~/.Xresources but no dice

```
pmenu.font = "monospace:size=9,DejaVuSansMono:size=9"
pmenu.background_color = "#000000"
pmenu.foreground_color = "#FFFFFF"
pmenu.selbackground_color = "#3465a4"
pmenu.selforeground_color = "#FFFFFF"
pmenu.separator_color = "#555753"
pmenu.border_color = "#555753"
pmenu.border_pixels = 2
pmenu.separator_pixels = 1
pmenu.diameter_pixels = 200
pmenu.separatorbeg = 0.14
pmenu.separatorend = 0.37
pmenu.triangle_width = 3
pmenu.triangle_height = 7
pmenu.triangle_distance = 6
```

**Comment by phillbush** [comment]
The X resources have different syntax from the config.h fields.  
Try to use that:

```
pmenu.font = "monospace:size=9,DejaVuSansMono:size=9"
pmenu.background = "#000000"
pmenu.foreground = "#FFFFFF"
pmenu.selbackground = "#3465a4"
pmenu.selforeground = "#FFFFFF"
pmenu.separator = "#555753"
pmenu.border = "#555753"
pmenu.borderWidth = 2
pmenu.separatorWidth = 1
pmenu.diameterWidth = 200
```

**Comment by GanerCodes** [comment]
Didn't fix it. However I have been noticing a possible related issue, if I run it without root I'll often get this error
```
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Serial number of failed request:  87
  Current serial number in output stream:  94
```
If I run it as root it works just without any text

**Comment by phillbush** [comment]
By "running as root" are you referring to the "root mode", where pmenu listen to events to the root window?  
(This has nothing to do with the root user, but as the root of the X11 window tree).

Try to run pmenu in other desktop environment or standalone window manager.  
Does the problem only occur on KDE?

**Comment by phillbush** [comment]
Can you show a screenshot of bad-rendered text on pmenu?  
Also, post the output of `xrdb -query`.

**Comment by GanerCodes** [comment]
I was talking about running it as superuser, I'm just testing with the default `pmenu.sh` script. It not starting at all doesn't always happen just sometimes

![image](https://user-images.githubusercontent.com/34655998/153863837-896410c2-bf01-45f6-b945-c13eb0c7f584.png)


```
[Ganer pmenu] xrdb -query
Xcursor.size:   48
Xcursor.theme:  Sweet-cursors
Xft.antialias:  1
Xft.dpi:        0
Xft.hinting:    1
Xft.hintstyle:  hintfull
Xft.rgba:       rgb
```

**Comment by phillbush** [comment]
You should not run it as super user, pmenu is a graphical application launcher and those kind of programs are not meant to be used by the super user.

I'm still thinking that plasma overwrote the X11 resources.  
Try to run this, and then try to run pmenu again:
```
echo "pmenu.foreground: #FFFFFF" | xrdb -merge -
```

**Comment by GanerCodes** [comment]
This didn't change anything, I think it might have something to do with fonts in general? not sure

**Comment by phillbush** [comment]
I sincerely don't know what could be wrong.  
Plasma installs a lot of files and changes considerably the environment (envvars, X resources, config files, etc), it can be anything.

And since you are not sure what could be the cause of the problem and cannot provide information on how to reproduce it, I'm afraid I could not help on it.

**Comment by GanerCodes** [comment]
spontaniously fixed itself after messing around with some security settings, sddm, updating, etc. No idea what caused or fixed it but its good now lol
