### ISSUE TITLE
Don't exit if icons are missing

### ISSUE THREAD

**Issue by jzbor** [phillbush/pmenu#15]
Hi,
I have an issue where pmenu refuses to run (one-shot), when icons are specified, but not found in the filesystem. `xmenu` just prints a warning and ignores the icon for that option, while `pmenu` just exits after returning. It would be nice, if `pmenu` would act the same.

Let me know what you think of it...

**Comment by phillbush** [comment]
Done. It should work now.  
I fixed both your issues on xmenu and forgot to fix on πmenu...

**Comment by jzbor** [comment]
Thanks a lot!
