### ISSUE TITLE
Open πmenu from anywhere with just a mouse click

### ISSUE THREAD

**Issue by grimnight** [phillbush/pmenu#17]
My mouse has extra buttons, one of which is currently without use. I would like to be able to open πmenu anywhere just by clicking the mouse button.

**Comment by phillbush** [comment]
With this last commit, you can now use the `-x` (or the `-X` option, if you want to pass the click to the root window) with the `0` modifier to mean "no modifier at all".

So, for example, if you want to open πmenu with the mouse button 8 and with no modifier, run πmenu like this:

```
$ pmenu -x 0-8 <myfile | sh &
```

I also add an `-e` option to automatically run the output string in `sh(1)`, so you do not need to pipe to sh.

**Comment by grimnight** [comment]
Wow, that was fast. Thank you. It works.
