### ISSUE TITLE
Heads-up: pmenu has been packaged for FreeBSD

### ISSUE THREAD

**Issue by 0mp** [phillbush/pmenu#5]
https://www.freshports.org/x11/pmenu/

Cheers!

**Comment by phillbush** [comment]
With the last release, πmenu now uses XRender to draw anti-aliased graphics (the line separators, and the slices).

Also, you do not need xclickroot anymore: with the `-r 3` option, pie menu can be run in background (by following it with a `&`) and it will watch for clicks on the root window. I included this xclickroot functionality into πmenu so it is always loaded, and it does not have the overhead of initiating and drawing stuff.

**Comment by 0mp** [comment]
Thanks a lot, I've already received a notification from the FreeBSD service for detecting new versions of software (https://portscout.freebsd.org/0mp@freebsd.org.html). Thanks for the heads-up, anyway! I'll update the port of pmenu soon!
