### ISSUE TITLE
Cursor jumping behavior

### ISSUE THREAD

**Issue by souew** [phillbush/pmenu#7]
It's somewhat frustrating to fight the menu when it constantly grabs your cursor and throws it to the center. I mean specifically when your cursor exits the circle, and then you want to go back, but as soon as the cursor touches the circle edge pmenu grabs it and throws it to the center, completely stuns me about where my cursor was and where I will end up in another second.
I think the perfect solution is to jump to the center only once after each circle spawn, but then leave the cursor alone, so that user can exit the second sub menu, return to the first circle and point at whatever he wants without intervention.
But if this kind of thing is difficult to implement, second best option is to make jumping behavior toggable in config.h

**Comment by phillbush** [comment]
Fixed!  
Now the pointer is warped (that's the X11 terminology) to the center of a pie menu only when it is created, not when the pointer enters it.
