### ISSUE TITLE
Sub menus don't work with Wacom tablet

### ISSUE THREAD

**Issue by souew** [phillbush/pmenu#8]
Graphic tablets have absolute cursor positioning, so I just tested, when I open second menu cursor jumps to the center, but immediately jumps back to where it was (because of absolute positioning of the tablet). So If you have a tablet you can't open second menus.
Demo:
https://fastupload.co/1085111
I think using radial menus with a tablet is very intuitive, so it would be nice to have pmenu support tablets. Maybe adding jump toggle to the config?

**Comment by souew** [comment]
It is possible to open it, if you flick your pen quickly to the second menu, but if you are too slow it won't open. And if you click on spot it also doesn't open.

**Comment by phillbush** [comment]
Just added a `-w` option for the Wacom-mode, which disables pointer warping.
